# frozen_string_literal: true

source "https://rubygems.org"

ruby "~> 3.4.2"

gem "byebug"
gem "fido_metadata", github: 'bdewater/fido_metadata'
gem "puma", "~> 6.6"
gem "rack-contrib"
gem "rackup", "~> 2.2"
gem "rubyzip"
gem "sinatra", "~> 4.0"
gem "sinatra-contrib"
gem "webauthn", path: File.join("..", "..")
gem "webrick", "~> 1.9"
