inherit_mode:
  merge:
    - AllowedNames

AllCops:
  TargetRubyVersion: 2.3
  DisabledByDefault: true
  Exclude:
    - "gemfiles/**/*"

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Layout:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/support/seeds.rb

Layout/MultilineAssignmentLayout:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Lint:
  Enabled: true

Naming:
  Enabled: true

Naming/MethodParameterName:
  AllowedNames:
    - rp

Security:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/BracesAroundHashParameters:
  Enabled: true

Style/CaseEquality:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true

Style/ClassMethods:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/Dir:
  Enabled: true

Style/EachForSimpleLoop:
  Enabled: true

Style/EachWithObject:
  Enabled: true

Style/EmptyBlockParameter:
  Enabled: true

Style/EmptyCaseCondition:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/EmptyLambdaParameter:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Style/EvenOdd:
  Enabled: true

Style/ExpandPathArguments:
  Enabled: true

Style/For:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GlobalVars:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/IdenticalConditionalBranches:
  Enabled: true

Style/IfInsideElse:
  Enabled: true

Style/InverseMethods:
  Enabled: true

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/MultilineMemoization:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Style/NestedParenthesizedCalls:
  Enabled: true

Style/OptionalArguments:
  Enabled: true

Style/ParenthesesAroundCondition:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantConditional:
  Enabled: true

Style/RedundantException:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

Style/RedundantInterpolation:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/RedundantPercentQ:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/Semicolon:
  Enabled: true

Style/SingleLineMethods:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: true

Style/SymbolLiteral:
  Enabled: true

Style/TrailingBodyOnClass:
  Enabled: true

Style/TrailingBodyOnMethodDefinition:
  Enabled: true

Style/TrailingBodyOnModule:
  Enabled: true

Style/TrailingMethodEndStatement:
  Enabled: true

Style/TrivialAccessors:
  Enabled: true

Style/UnpackFirst:
  Enabled: true

Style/YodaCondition:
  Enabled: true

Style/ZeroLengthPredicate:
  Enabled: true
